version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://172.17.0.1:21051/xfactor
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 22031:3000
    depends_on:
      - redis
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - xfactor

  redis:
    container_name: woofie-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - xfactor

volumes:
  redis-data:

networks:
  xfactor:
    driver: bridge
